# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parking Manager' do
	  # Comment the next line if you don't want to use dynamic frameworks
	  use_frameworks!

	  # Pods for Parking Manager
	  # Add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'

	# Add the pods for any other Firebase products you want to use in your app
	# For example, to use Firebase Authentication and Cloud Firestore
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
	pod 'Firebase/Storage'

end